add_newline = false
command_timeout = 800

format = """
[](#FFFFFF)🌹  [](bold #FFFFFF)$username\
[](#FFFFFF) at [](bold #FFFFFF)$hostname\
[](#FFFFFF) in [](bold #FFFFFF)$directory\
[](#FFFFFF) on [](bold #FFFFFF)$git_branch\
[](#FFFFFF)$git_status
[](fg:#FFFFFF)🕊️ [](fg:#FFFFFF)$time\
[](#FFFFFF)
[](bold #FFFFFF)$character\
"""

[username]
style_user = "#FFFFFF"
style_root = "#FFFFFF"
format = "[$user]($style)"
show_always = true

[hostname]
style = "#FFFFFF"
format = "[$hostname]($style)"
ssh_only = false

[directory]
style = "#FFFFFF"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "#FFFFFF"
format = "[\\($branch\\)]($style)"

[git_status]
style = "#FFFFFF"
format = " [$all_status$ahead_behind]($style)"
conflicted = "⚔️$count"
ahead = "🌱$count"
behind = "🌙$count"
diverged = "🌀$count"
untracked = "🌫️$count"
stashed = "📦$count"
modified = "🖋️$count"
staged = "✨$count"
renamed = "🔄$count"
deleted = "💔$count"

[time]
disabled = false
style = "#FFFFFF"
time_format = "%Y-%m-%d %H:%M"
format = "[ $time]($style)"

[character]
format = "$symbol"
success_symbol = "[🌹](bold #FFFFFF)"
error_symbol = "[🥀](bold #FFFFFF)"

[cmd_duration]
disabled = true

[memory_usage]
disabled = true

[jobs]
disabled = true
