[flavor]
dark = ""   # no base flavor
light = ""  # no base flavor


# ======================
# Manager styles
# ======================
[mgr]
cwd             = { fg = "white", bg = "black", bold = true }
hovered         = { fg = "lightgray", bg = "darkgray" }
preview_hovered = { fg = "white", bg = "black" }  # changed to white text on black
find_keyword    = { fg = "white", bg = "black", bold = true }
find_position   = { fg = "lightgray", bg = "black", italic = true }

marker_copied   = { fg = "gray", bg = "black" }
marker_cut      = { fg = "gray", bg = "black" }
marker_marked   = { fg = "lightgray", bg = "black" }
marker_selected = { fg = "white", bg = "darkgray", bold = true }

count_copied    = { fg = "gray", bg = "black" }
count_cut       = { fg = "gray", bg = "black" }
count_selected  = { fg = "white", bg = "darkgray" }

border_symbol   = "│"
border_style    = { fg = "gray", bg = "black" }

syntect_theme   = ""  # no tmTheme, monochrome only



# ======================
# Tabs
# ======================
[tabs]
active   = { fg = "white", bg = "darkgray", bold = true }
inactive = { fg = "lightgray", bg = "black" }
sep_inner = { open = "[", close = "]" }
sep_outer = { open = "", close = "" }

# ======================
# Mode styles
# ======================
[mode]
normal_main  = { fg = "white", bg = "black" }
normal_alt   = { fg = "lightgray", bg = "black" }
select_main  = { fg = "white", bg = "darkgray" }
select_alt   = { fg = "lightgray", bg = "darkgray" }
unset_main   = { fg = "gray", bg = "black" }
unset_alt    = { fg = "darkgray", bg = "black" }

# ======================
# Status bar
# ======================
[status]
overall       = { fg = "white", bg = "black" }
sep_left      = { open = "", close = "]" }
sep_right     = { open = "[", close = "" }
perm_type     = { fg = "gray", bg = "black" }
perm_read     = { fg = "gray", bg = "black" }
perm_write    = { fg = "gray", bg = "black" }
perm_exec     = { fg = "white", bg = "black" }
perm_sep      = { fg = "gray", bg = "black" }
progress_label = { fg = "white", bg = "black" }
progress_normal= { fg = "white", bg = "darkgray" }
progress_error = { fg = "white", bg = "red" } # optional accent

# ======================
# Which-key / Key hints
# ======================
[which]
cols = 2
mask = { fg = "gray", bg = "black" }
cand = { fg = "white", bg = "darkgray" }
rest = { fg = "lightgray", bg = "black" }
desc = { fg = "white", bg = "black" }
separator = " -> "
separator_style = { fg = "gray", bg = "black" }

# ======================
# Confirmation dialogs
# ======================
[confirm]
border = { fg = "gray", bg = "black" }
title  = { fg = "white", bg = "black", bold = true }
content= { fg = "lightgray", bg = "black" }
list   = { fg = "white", bg = "darkgray" }
btn_yes= { fg = "white", bg = "darkgray" }
btn_no = { fg = "white", bg = "darkgray" }
btn_labels = ["Yes","No"]

# ======================
# Pick list
# ======================
[pick]
border   = { fg = "gray", bg = "black" }
active   = { fg = "white", bg = "darkgray" }
inactive = { fg = "lightgray", bg = "black" }

# ======================
# Input fields
# ======================
[input]
border   = { fg = "gray", bg = "black" }
title    = { fg = "white", bg = "black", bold = true }
value    = { fg = "lightgray", bg = "black" }
selected = { fg = "white", bg = "darkgray", bold = true }


# ======================
# Filetype rules
# ======================
[filetype]
rules = [
    { name = "*", fg = "white" },
    { name = "*/", fg = "white" }
]


[syntax]
comment  = { fg = "gray" }        # comments in gray
keyword  = { fg = "white", bold = true } # keywords in white
string   = { fg = "lightgray" }   # strings in light gray
number   = { fg = "lightgray" }   # numbers in light gray
function = { fg = "white" }       # function names in white
type     = { fg = "white", bold = true } # types in white bold
constant = { fg = "lightgray" }   # constants in light gray

