# ======================
# General
# ======================
[general]
# Default directory to open
default_path = "~"
export EDITOR=nvim

# Whether to auto-refresh file list
auto_refresh = true

# Show hidden files by default
show_hidden = true

# Confirm before deleting files
confirm_delete = true

# Default sort order: name / size / modified
sort_by = "name"
sort_reverse = false

# Preview behavior
preview = true         # enable/disable preview pane
preview_auto = true    # auto-update preview when moving cursor
preview_width = 50     # columns reserved for preview pane

# Tabs
tabs_enabled = true
tabs_wrap = false


[file_ops]
# Confirm actions
confirm_copy = true
confirm_cut  = true
confirm_paste= true

# Clipboard behavior
clipboard_integration = true

# Default markers for visual selection
default_marker = "*"



[features]
# Enable mouse support
mouse = true

# Enable icons (set to false if you want no icons)
icons = false

# Enable filetype-specific behavior
filetype_detection = true

# Enable git integration (shows git status in file list)
git_integration = true

# Enable syntax highlighting in preview
syntax_highlight = false

