(define-module (substrate user-space root loaders desktop)
  #:use-module (substrate user-space root desktop seatd)
  #:use-module (substrate user-space root desktop hyprland)
  #:use-module (substrate user-space root desktop hypridle)
  #:use-module (substrate user-space root desktop qutebrowser)
  #:use-module (substrate user-space root desktop quickshell)
  #:use-module (substrate user-space root desktop dms dms)
  #:use-module (substrate user-space root desktop mako)
  #:use-module (substrate user-space root desktop wallpaper mpvpaper)
  #:use-module (substrate user-space root desktop wallpaper swww)
  #:use-module (substrate user-space root desktop pyprland)
  #:use-module (substrate user-space root desktop hyprsunset)
  #:use-module (substrate user-space root desktop hyprvim)
  #:use-module (substrate user-space root desktop greetd)
  #:use-module (substrate user-space root desktop 3d blender)
  #:use-module (substrate user-space root desktop image krita)
  #:use-module (substrate user-space root desktop video mpv)
  #:use-module (substrate user-space root desktop video ffmpeg)
  #:use-module (substrate user-space root desktop video obs)
  #:use-module (substrate user-space root desktop video obs-cli)
  #:use-module (substrate user-space root desktop video kdenlive)
  #:use-module (substrate user-space root desktop video gst-editing-services)
  #:use-module (substrate user-space root desktop video mlt)
  #:use-module (substrate user-space root desktop video opentimelineio)
  #:use-module (substrate user-space root desktop video xytz)
  #:use-module (substrate user-space root desktop wayland grim)
  #:use-module (substrate user-space root desktop wayland slurp)
  #:use-module (substrate user-space root desktop wayland swappy)
  #:use-module (substrate user-space root desktop wayland wl-clipboard)
  #:use-module (substrate user-space root desktop wayland wlogout)
  #:use-module (substrate user-space root desktop wayland cliphist)
  #:use-module (substrate user-space root desktop wayland grimblast)
  #:use-module (substrate user-space root desktop wayland wofi)
  #:use-module (gnu packages imagemagick)
  #:use-module (gnu packages web)
  #:use-module (gnu packages xdisorg)
  #:re-export (seatd seatd-service hyprland hypridle hyprvim qutebrowser quickshell mako mpvpaper swww imagemagick jq python-pyprland hyprsunset greetd blender mpv ffmpeg obs obs-cli kdenlive gst-editing-services mlt opentimelineio xytz grim slurp swappy wl-clipboard wlogout cliphist grimblast dms wofi)
  #:export (root-desktop-packages))

(define-public root-desktop-packages
  (list seatd hyprland hypridle hyprvim qutebrowser quickshell mako mpvpaper swww imagemagick jq python-pyprland hyprsunset greetd blender mpv ffmpeg obs obs-cli kdenlive gst-editing-services mlt opentimelineio xytz grim slurp swappy wl-clipboard wlogout cliphist grimblast dms wofi))
