# Monochrome Theme
# Author: ChatGPT x User (Remade for Visibility)
# A crisp grayscale theme with subtle contrast — perfect for focus and retro-terminal vibes.

# Code syntax highlight theme (You might need a syntax theme that works with black background,
# e.g., 'monokai', 'dracula', or 'github-dark')
code_syntax_highlight = "monochrome"

# ========= Border =========
# Subtle dark gray border for separation
file_panel_border = "#333333"
sidebar_border = "#333333"
footer_border = "#333333"

# ========= Border Active =========
# Lighter gray for active focus
file_panel_border_active = "#888888"
sidebar_border_active = "#888888"
footer_border_active = "#888888"
modal_border_active = "#AAAAAA"

# ========= Background (bg) =========
# Pure Black Background
full_screen_bg = "#000000"
file_panel_bg = "#000000"
sidebar_bg = "#000000"
footer_bg = "#000000"
modal_bg = "#000000"

# ========= Foreground (fg) =========
# Pure White Text (Foreground)
full_screen_fg = "#FFFFFF"
file_panel_fg = "#FFFFFF"
sidebar_fg = "#FFFFFF"
footer_fg = "#FFFFFF"
modal_fg = "#FFFFFF"

# ========= Special Color =========
# Key colors using various shades of gray/white for visibility
cursor = "#FFFFFF"
correct = "#BBBBBB" # For confirmation/success messages
error = "#FF5555"   # Use a strong red for errors to break the monochrome
hint = "#AAAAAA"    # Less important information
cancel = "#777777"  # Gray for cancellation/less important actions
# Gradient color can only have two color! (Using two shades of gray/white)
gradient_color = ["#DDDDDD", "#AAAAAA"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#888888"
file_panel_top_path = "#DDDDDD"
# Highlight selected item with a subtle dark gray background
file_panel_item_selected_fg = "#FFFFFF"
file_panel_item_selected_bg = "#1A1A1A"

# ========= Sidebar Special Items =========
sidebar_title = "#BBBBBB"
sidebar_item_selected_fg = "#FFFFFF"
sidebar_item_selected_bg = "#1A1A1A"
sidebar_divider = "#333333"

# ========= Modal Special Items =========
# White text on black/gray button backgrounds
modal_cancel_fg = "#FFFFFF"
modal_cancel_bg = "#333333"

modal_confirm_fg = "#FFFFFF"
modal_confirm_bg = "#555555"

# ========= Help Menu =========
help_menu_hotkey = "#FFFFFF"
help_menu_title = "#DDDDDD"
