hl.curve("snap",        { type = "bezier", points = { {0.05, 0.9},  {0.1,  1.0}  } })
hl.curve("snapLight",   { type = "bezier", points = { {0.1,  0.9},  {0.2,  1.0}  } })
hl.curve("eject",       { type = "bezier", points = { {0.8,  0.0},  {1.0,  0.15} } })
hl.curve("swell",       { type = "bezier", points = { {0.1,  1.8},  {0.25, 1.0}  } })
hl.curve("pulseSharp",  { type = "bezier", points = { {0.5,  0.0},  {0.2,  1.0}  } })
hl.curve("pulseBig",    { type = "bezier", points = { {0.25, 0.0},  {0.1,  1.0}  } })
hl.curve("bounce",      { type = "bezier", points = { {0.3,  1.6},  {0.4,  1.0}  } })
hl.curve("fastIn",      { type = "bezier", points = { {0.35, 0.0},  {0.6,  1.0}  } })
hl.curve("springSnap",  { type = "spring", mass = 1, stiffness = 300, dampening = 25 })
hl.curve("springHard",  { type = "spring", mass = 1, stiffness = 500, dampening = 30 })
hl.curve("springBouncy",{ type = "spring", mass = 1, stiffness = 800, dampening = 40 })

hl.animation({ leaf = "global",        enabled = true, speed = 4,   bezier = "snap"                              })
hl.animation({ leaf = "border",        enabled = true, speed = 3,   bezier = "pulseSharp"                        })
hl.animation({ leaf = "windows",       enabled = true, speed = 3,   spring = "springBouncy", style = "popin 60%" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 1.5, bezier = "snap",         style = "popin 80%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 2.5, bezier = "eject",        style = "popin 20%" })
hl.animation({ leaf = "windowsMove",   enabled = true, speed = 3,   spring = "springSnap",   style = "slide"     })
hl.animation({ leaf = "fade",          enabled = true, speed = 3,   bezier = "snap"  })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.5, bezier = "snap"  })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 3,   bezier = "snap"  })
hl.animation({ leaf = "layers",        enabled = true, speed = 3,   spring = "springSnap", style = "slide"       })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 3,   spring = "springHard", style = "popin 45%"   })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 3,   bezier = "eject",      style = "slide"       })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 3,   bezier = "pulseBig"                          })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 3,   bezier = "eject"                             })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 3,   bezier = "swell",      style = "slidefade 15%" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 3,   bezier = "swell",      style = "slidefade 15%" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 2.5, bezier = "eject",      style = "slidefade 15%" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 3,   spring = "springHard"                        })
