hl.env("XDG_DATA_DIRS", "/run/current-system/profile/share:/home/aoeu/.local/share")
hl.env("XCURSOR_SIZE", "10")
hl.env("HYPRCURSOR_SIZE", "10")
hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")
hl.env("XCURSOR_THEME", "rose-pine-hyprcursor")
hl.env("QT_QPA_PLATFORM_PLUGIN_PATH", "/gnu/store/z81b0r2nv3zgvsx5zylxxkfjrd3bq365-qtwayland-6.9.2/lib/qt6/plugins/platforms")