let light_theme = {
    separator: "#FFFFFF"
    leading_trailing_space_bg: { attr: n }
    header: { fg: "#FFFFFF" attr: b }
    empty: "#FFFFFF"
    bool: "#FFFFFF"
    int: "#FFFFFF"
    filesize: "#FFFFFF"
    duration: "#FFFFFF"
    date: "#FFFFFF"
    range: "#FFFFFF"
    float: "#FFFFFF"
    string: "#FFFFFF"
    nothing: "#FFFFFF"
    binary: "#FFFFFF"
    cell-path: "#FFFFFF"
    row_index: "#FFFFFF"
    record: "#FFFFFF"
    list: "#FFFFFF"
    block: "#FFFFFF"
    hints: "#FFFFFF"
    search_result: { fg: "#FFFFFF" }
    shape_and: "#FFFFFF"
    shape_binary: "#FFFFFF"
    shape_block: "#FFFFFF"
    shape_bool: "#FFFFFF"
    shape_closure: "#FFFFFF"
    shape_custom: "#FFFFFF"
    shape_datetime: "#FFFFFF"
    shape_directory: "#FFFFFF"
    shape_external: "#FFFFFF"
    shape_externalarg: "#FFFFFF"
    shape_external_resolved: "#FFFFFF"
    shape_filepath: "#FFFFFF"
    shape_flag: "#FFFFFF"
    shape_float: "#FFFFFF"
    shape_garbage: { fg: "#FFFFFF" attr: b }
    shape_glob_interpolation: "#FFFFFF"
    shape_globpattern: "#FFFFFF"
    shape_int: "#FFFFFF"
    shape_internalcall: "#FFFFFF"
    shape_keyword: "#FFFFFF"
    shape_list: "#FFFFFF"
    shape_literal: "#FFFFFF"
    shape_match_pattern: "#FFFFFF"
    shape_matching_brackets: { attr: u }
    shape_nothing: "#FFFFFF"
    shape_operator: "#FFFFFF"
    shape_or: "#FFFFFF"
    shape_pipe: "#FFFFFF"
    shape_range: "#FFFFFF"
    shape_record: "#FFFFFF"
    shape_redirection: "#FFFFFF"
    shape_signature: "#FFFFFF"
    shape_string: "#FFFFFF"
    shape_string_interpolation: "#FFFFFF"
    shape_table: "#FFFFFF"
    shape_variable: "#FFFFFF"
    shape_vardecl: "#FFFFFF"
    shape_raw_string: "#FFFFFF"
}

let light_theme = $light_theme
