#!/bin/sh
# Create the build system.

set -e -x

# Generate stubs for translations.
langs=`find po/doc -type f -name 'Manifolding-OS-manual*.po' \
        | sed -e 's,.*/Manifolding-OS-manual\.,,;s,\.po$,,'`
for lang in ${langs}; do
    if [ ! -e "doc/Manifolding-OS.${lang}.texi" ]; then
	echo "@setfilename Manifolding-OS.${lang}.info" > "doc/Manifolding-OS.${lang}.texi"
	echo "@include version-${lang}.texi" >> "doc/Manifolding-OS.${lang}.texi"
	# Ensure .po file is newer.
	touch "po/doc/Manifolding-OS-manual.${lang}.po"
    fi
done
langs=`find po/doc -type f -name 'Manifolding-OS-cookbook*.po' \
        | sed -e 's,.*/Manifolding-OS-cookbook\.,,;s,\.po$,,'`
for lang in ${langs}; do
    if [ ! -e "doc/Manifolding-OS-cookbook.${lang}.texi" ]; then
	echo "@setfilename Manifolding-OS-cookbook.${lang}.info" > "doc/Manifolding-OS-cookbook.${lang}.texi"
	# Ensure .po file is newer.
	touch "po/doc/Manifolding-OS-cookbook.${lang}.po"
    fi
done

autoreconf -vfi

# Replace Automake's build-aux/mdate-sh with build-aux/mdate-from-git, our
# own, reproducible version.
chmod +w build-aux/mdate-sh
rm -f build-aux/mdate-sh
ln -s mdate-from-git.scm build-aux/mdate-sh
